real_marker_amass_splits:
  vald:
  - HumanEva
  - ACCAD
  - TotalCapture
  train:
  - CMU
  - Transitions
  - PosePrior
  - CAESAR_SMPLx_betas
synthetic_body_amass_splits:
  vald:
  - HumanEva
  - ACCAD
  - TotalCapture
  train:
  - CMU
  - Transitions
  - PosePrior
  - CAESAR_SMPLx_betas
superset_fname: /home/divyeshjohri/Documents/SOMA/data/V48_02_SOMA/marker_dataset/superset.json # /is/cluster/scratch/nghorbani/soma/data/V48_01_SOMA/marker_dataset/superset.json
wrist_markers_on_stick: false
use_real_data_for: null
use_synt_data_for:
- train
- vald
body_dataset_dir: /home/divyeshjohri/Documents/SOMA/support_files/smplx/body_dataset # /ps/project/soma/support_files/release_soma/smplx/training_body_parameters/V48_01/body_dataset
surface_model_fname: /home/divyeshjohri/Documents/SOMA/support_files/smplx/neutral/model.npz # /ps/project/soma/support_files/release_soma/smplx/neutral/model.npz
num_random_vid_ring: 1
enable_rnd_vid_on_face_hands: false
num_marker_layout_augmentation: 1
babel: null
num_prop_marker_max: 0
unified_frame_rate: 30
num_hand_var_perseq: 15
num_betas: 10
num_expressions: 80
gender: neutral
amass_pkl_dir: /home/divyeshjohri/Documents/SOMA/support_files/smplx/amass_neutral
num_timeseq_frames: 1
num_frames_overlap: 0
